image::https://astral.sh/static/SVG/UV.svg[UV]

This is the snap for UV, an extremely fast Python package installer and resolver, written in Rust.

== Supported Architectures

`amd64` and `arm64`

== Release Instructions

Each UV feature release has its own corresponding branch in this repository.
These branches follow the naming convention `release/X.Y`.
When an official UV release is made, create or checkout the branch tracking that feature release.
The link:.github/workflows/build-snap-packages.yml[GitHub workflow file] must be updated with the appropriate feature release version and publishing track for that branch and version.
The other UV release version details in that file will determine the version of the snap that is built.
Only tagged releases will upload and publish snaps.
Set the release track to `candidate` for release candidates, or `stable` for regular releases.

CI jobs only publish snap packages to the specified release track.
If publishing for the latest feature release, an extra manual step is required.
The `latest` channel needs to be updated in the https://snapcraft.io/uv/releases[Snapcraft Releases] area (login required).
This should be a simple matter of promoting the just-published snaps to the relevant channel (`latest/candidate` or `latest/stable`).
If this is the first regular release after previous release candidates, also close the `latest/candidate` channel after promoting to `latest/stable`.
The candidate channel will then forward to the latest stable release, which ensures anyone tracking the candidate channel moves up to the stable release on their next update.