name: Build snaps

env:
  UV_FEATURE_RELEASE: "0.1"
  UV_PATCH_RELEASE: "44"
  UV_RELEASE_SUFFIX: ""
  SNAP_RELEASE_TRACK: edge

on:
  push:
    tags:
      - 'release/**'

jobs:
  build-snap:
    name: Build and publish (${{ matrix.runs-on }})
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, buildjet-2vcpu-ubuntu-2204-arm ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3
      - name: Apply CMake version to snapcraft.yaml
        run: sed -E 's+@UV_VERSION@+${{ env.UV_FEATURE_RELEASE }}.${{ env.UV_PATCH_RELEASE }}${{ env.UV_RELEASE_SUFFIX }}+g' local/snapcraft.yaml.in > snapcraft.yaml
        working-directory: ./snap
      - name: Build snap
        id: build
        uses: snapcore/action-build@v1
      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ env.UV_FEATURE_RELEASE }}/${{ env.SNAP_RELEASE_TRACK }}